"""initial tables

Revision ID: 1af1999c0b36
Revises: 
Create Date: 2026-02-13 20:40:02.865081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af1999c0b36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True, comment='会话标题'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active/archived'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='房源名称'),
    sa.Column('address', sa.String(length=500), nullable=False, comment='地址'),
    sa.Column('room_type', sa.String(length=50), nullable=False, comment='房型'),
    sa.Column('area', sa.Float(), nullable=False, comment='面积(平方米)'),
    sa.Column('facilities', sa.JSON(), nullable=False, comment='设施配置'),
    sa.Column('description', sa.Text(), nullable=True, comment='房源描述'),
    sa.Column('min_price', sa.Float(), nullable=True, comment='最低可接受价'),
    sa.Column('max_price', sa.Float(), nullable=True, comment='最高价格'),
    sa.Column('expected_return_rate', sa.Float(), nullable=True, comment='期望收益率'),
    sa.Column('vacancy_tolerance', sa.Float(), nullable=True, comment='空置容忍度(0-1)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='user/assistant/system/tool'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True, comment='工具调用记录'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False, comment='目标日期'),
    sa.Column('conservative_price', sa.Float(), nullable=False, comment='保守价'),
    sa.Column('suggested_price', sa.Float(), nullable=False, comment='建议价'),
    sa.Column('aggressive_price', sa.Float(), nullable=False, comment='激进价'),
    sa.Column('calculation_details', sa.JSON(), nullable=False, comment='计算依据明细'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False, comment='入住日期'),
    sa.Column('actual_price', sa.Float(), nullable=False, comment='实际成交价'),
    sa.Column('platform', sa.String(length=50), nullable=True, comment='来源平台'),
    sa.Column('advance_days', sa.Integer(), nullable=True, comment='提前预订天数'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pricing_record_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=20), nullable=False, comment='采纳/拒绝/调整'),
    sa.Column('actual_price', sa.Float(), nullable=True, comment='实际采用价格'),
    sa.Column('note', sa.Text(), nullable=True, comment='用户备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pricing_record_id'], ['pricing_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('transaction')
    op.drop_table('pricing_record')
    op.drop_table('message')
    op.drop_table('property')
    op.drop_table('conversation')
    # ### end Alembic commands ###
